updateContact
54Cat/petly-backend pull request #5
Opened 2023-01-30 15:24 UTC by bilagava

2023-01-30 18:31 UTC, 54Cat requested changes
нужно новая схема для обновления полей/поля юзера

2023-01-30 18:31 UTC, 54Cat commented on controllers/auth/updateContact.js
> +const { HttpError } = require('../../helpers');
переименуй на RequestError
файла с названием HttpError нет в пректе

2023-01-30 18:31 UTC, 54Cat commented on routes/api/auth.js
> +    validateBody(registerSchema),
думаю нужно новая схема с необязательными полями, чтоб была возможность обновлять одно любое поле

2023-01-30 21:48 UTC, bilagava commented on controllers/auth/updateContact.js
> +const { HttpError } = require('../../helpers');
Поправив

2023-01-30 21:48 UTC, bilagava commented on routes/api/auth.js
> +    validateBody(registerSchema),
Нову схему зробив

2023-01-31 07:46 UTC, 54Cat approved these changes

2023-01-31 07:59 UTC, 54Cat approved these changes

2023-01-31 08:17 UTC, merged